name: Robot Framework Tests Frontend

on:
  pull_request:
    branches:
      - main
      
jobs:
  robot-framework-testes-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests  
          pip install robotframework-faker     

      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Robot Framework Tests
        run: |
          cd robot-framework-testes-frontend
          robot --outputdir results tests/
        continue-on-error: true

      - name: Check Test Results
        run: |
          cd robot-framework-testes-frontend/results
          if grep -q "FAIL" output.xml; then
            echo "❌ Testes falharam!"
            exit 1
          else
            echo "✅ Todos os testes passaram!"
          fi